### ISSUE TITLE
A bug in chapter02/question2.4/LinkedListPartitioner

### ISSUE THREAD

**Issue by monkeyWzr** [careercup/CtCI-6th-Edition-php#3]
I think there's a bug in LinkedListPartitioner at line 17 ($node = $previousNode;):

```php
<?php
require_once __DIR__ . '/../../lib/Node.php';

class LinkedListPartitioner {
    public static function partition(Node $node, $x) {
        $head = $node;
        $previousNode = null;
        while ($node !== null) {
            if ($node->getData() < $x && $previousNode !== null) {
                // remove the node from this part of the list
                $previousNode->setNext($node->getNext());
                // put this node at the begining of the list
                $node->setNext($head);
                // reset head
                $head = $node;
                // reset node for the next iteration
                $node = $previousNode;
            } else {
                $previousNode = $node;
                $node = $node->getNext();
            }
        }
        return $head;
    }
}
```
If there is more than one nodes at the front of the list that are less than `$x`, the iteration will be stuck at the second node because the `$previousNode` and the `$node` point to the same place. You can change the value array in the test to `[ 1,2,3,4,5,6 ]` with `$x`still equal to 5, then run the test and find out. 

### Quick solution to fix it:

change the code at line 17 to:
```php
$node = $node->getNext();
```

**Comment by asaph** [comment]
@monkeyWzr Thank you for pointing out this issue. I just replaced this buggy solution with a more elegant one that builds 2 separate linked lists: one for the values less than `$x`, and another for the values greater than or equal to `$x`. At the end the 2 lists are joined together. See commit e1fa34f322245b3201e8549f8653f94068f8c139. Thanks again!
