### ISSUE TITLE
Wrong test case implementations for chapter16/question16.03

### ISSUE THREAD

**Issue by outcompute** [careercup/CtCI-6th-Edition-php#4]
The following two cases are wrong, as instead of checking if the returned point lies on the lines, are matching against a pre-selected point.
```
    public function testGetPointOfIntersectonWith2OverlappingVerticalLines() {
        $point = Intersection::getPointOfIntersecton([ 2, 0 ], [ 2, 10 ], [ 2, 8 ], [ 2, 16 ]);
        $expected = [ 2, 10 ];
        $this->assertEquals($expected, $point);
    }

    public function testGetPointOfIntersectonWith2OverlappingLines() {
        $point = Intersection::getPointOfIntersecton([ 2, 3 ], [ 4, 6 ], [ 4, 6 ], [ 6, 9 ]);
        $expected = [ 4, 6 ];
        $this->assertEquals($expected, $point);
    }
```

And the below test case is checking for null when the lines represented by the points in the test case do actually intersect as [evidenced here](https://www.wolframalpha.com/input/?i=line+through+(1,4)+and+(2,3)+and+line+through+(0,0)+and+(5,5)): 
```
    public function testGetPointOfIntersectonWithNoIntersection() {
        $point = Intersection::getPointOfIntersecton([ 0, 0 ], [ 5, 5 ], [ 1, 4 ], [ 2, 3 ]);
        $this->assertNull($point);
    }
```

**Comment by asaph** [comment]
I don't have the book handy with me ATM but I believe this question is about [line segments](https://en.wikipedia.org/wiki/Line_segment), rather than [lines](https://en.wikipedia.org/wiki/Line_(geometry)#In_Euclidean_geometry). A line segment doesn't include the line extending beyond the 2 points. I'll double check later when I have the book handy and give you an update.

**Comment by outcompute** [comment]
Completely missed that. Apologies.
Then only the 'testGetPointOfIntersectonWith2OverlappingVerticalLines' case needs revisiting to include points within (2,8) to (2,10), and everything else is fine.

**Comment by asaph** [comment]
@outcompute I wouldn't say the test was "wrong" as it did validate one possible correct answer. But I did make a change in commit 86c1a0a412f8e514f3009804d6c96d69fe109eda which makes the test accept any valid point on the line segment (2,8) to (2,10). Thank you for the suggested improvement.
